project:
  type: book
  output-dir: docs
  resources:
    - /.nojekyll

book:
  title: "Fecal Indicator Bacteria and Hydrology"
  author: "Kim Cressman, Catbird Stats"
  date: today
  repo-url: https://github.com/tbep-tech/fibs-and-hydrology 
  repo-actions: [source]
  chapters:
    - index.qmd
    - data_sources.qmd
    - how_to_approach.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
  pdf:
    documentclass: scrreprt
    
warning: false
message: false
error: true



