# Data Sources

## Fecal Indicator Bacteria

All fecal indicator bacteria (FIB) data were downloaded from the [Water Quality Portal](https://www.waterqualitydata.us/), using `tbeptools::read_importwqp()`, from the following providers: Florida Department of Health (21FLDOH_WQX), Hillsborough County (21FLHILL_WQX), Manatee County (21FLMANA_WQX), Pasco County (21FLPASC_WQX), the Florida Department of Environmental Protection (21FLPDEM_WQX), and Polk County (21FLPOLK_WQX). The [file](https://github.com/tbep-tech/fibs-and-hydrology/blob/main/fib-data/tbeptools_importwqp.rds "link to tbeptools_importwqp.rds file") generated during the [Data Assessment](https://tbep-tech.github.io/fib-data-assessment/) portion of this project was re-used here. The script used for downloading and processing the data is [on github](https://github.com/tbep-tech/fib-data-assessment/blob/main/R/tbeptools_preprocessing.R "Script to import FIB data via tbeptools").

## Hydrologic Loads

[Monthly hydrologic load estimates](https://github.com/tbep-tech/fibs-and-hydrology/blob/main/hydro-load-data/monthly-hydrology.xlsx "link to monthly-hydrology.xlsx"), generated by Janicki Environmental, Inc., were downloaded from [TBEP's Nitrogen Loads dashboard](https://tbep.org/tampa-bay-nitrogen-loads/) \['Total Hydrologic Load (monthly, 1985 - 2021)' button\].

## Radar-estimated precipitation

Monthly and daily radar-estimated precipitation files, as well as a spatial layer containing the pixels for which estimates were made, were downloaded from the Southwest Florida Water Management District [(SWFWMD) ftp site](ftp://ftp.swfwmd.state.fl.us/pub/radar_rainfall/Monthly_Data/); that link was provided by the [Tampa Bay Water Atlas](https://tampabay.wateratlas.usf.edu/rainfall/estimates/).

These files are very large and are not committed in this github repository. Precipitation estimates of each type were processed using [this script](https://github.com/tbep-tech/fibs-and-hydrology/blob/main/R/rainfall_preprocessing.R "rainfall_preprocessing.R"), and resulting in a [monthly compiled rainfall file](https://github.com/tbep-tech/fibs-and-hydrology/blob/main/SWFWMD-rainfall-data/compiledRainfall.rds "link to compiledRainfall.rds") and a [daily compiled rainfall file](https://github.com/tbep-tech/fibs-and-hydrology/blob/main/SWFWMD-rainfall-data/Daily_Data/compiledDailyRainfall.rds "compiledDailyRainfall.rds").

## WBIDs

The shapefile of all of FL's Water Body IDs (WBIDs) from IWR Run 65 was downloaded from the [FDEP Geospatial website](https://geodata.dep.state.fl.us/datasets/FDEP::waterbody-ids-wbids/about "DEP WBID page").
